### ISSUE TITLE
Get the “copy to clipboard” icon working beneath each message

### ISSUE THREAD

**Issue by krschacht** [the-dot-bot/hostedgpt#109]
When you are chatting with the AI, there is a list of messages in the right column. When you hover over a message, two icons appear beneath it: a circle refresh icon and a clipboard icon.

We need to make the clipboard icon work. When you click it, the contents of the chat message should be copied to the user’s clipboard. There should be a javascript function that does this.

The naive implementation would just be to add an `onClick=“”` and call that function. But this should be done by creating a new stimulus controller (in javascript/controllers directory). There are many there already that can be referenced.

The tricky part of this will be how do we give the user visual feedback that says “Copied to clipboard”. What ChatGPT does it simply turn the copy icon into a check icon for a couple seconds. That's not the most clear, but it seems like a reasonable v1.

**Comment by Kaleshe** [comment]
Hi @krschacht I'd like to work on this. But could you please elaborate on the issue

**Comment by krschacht** [comment]
Hi @Kaleshe! I’m so curious how you found out about this project?? We are almost done wrapping up v0.5 which is a set of really core functionality. After that, I was going to start spreading the word to find contributors for it so I’m so curious how you already found out. :)

In any case, we’d love to get your help. Have you already forked the repository and is the app working for you? there might still be some issues with the core app functionality. We’re in the process of working through the final issues of back-and-forth chatting with GPT.

This task could be done even with the issues in place so you wouldn’t be blocked on it. I went ahead and elaborated on the task.

**Comment by Kaleshe** [comment]
Hi, I found it here https://goodfirstissues.com/ :)

I have forked the repo and I'm currently working on setting it up in my local env now

**Comment by krschacht** [comment]
Very nice @Kaleshe. Welcome to the project! :) My friend Rob and I are experienced engineers, but this is my first time creating an open source project so I'm figuring it out as I go. Let us know if you run into any issues getting set up.

Hopefully you are a ChatGPT user :) since this project is going to be an alternative version of it — first we'll get feature parity with it, then we'll start adding a bunch of features that ChatGPT doesn't have yet.

**Comment by Kaleshe** [comment]
Thanks! I'm also very new to contributing, made my first contribution yesterday :)

And that sounds awesome!

I have nearly got it all set up. I started up the server and received the following error `
```
connection to server at "127.0.0.1", port 5432 failed: fe_sendauth: no password supplied
```

**Comment by Kaleshe** [comment]
@krschacht I have tried setting up the local env using docker and get this error when I try to run the image `ArgumentError: Missing `secret_key_base` for 'production' environment`

**Comment by krschacht** [comment]
@Kaleshe Sorry about the trouble! I just did a fresh fork & fresh install on my dev environment. And I did a fresh fork & fresh install to Render. I discovered a BUNCH of little issues which we have now fixed. Could you start fresh and see if it works now?

Note: when you finally get to the chat interface and get your OpenAI key entered, when you send a chat message the AI won't reply yet. We are wrapping up two final PRs that will actually make the replies work, so that's coming really soon. But you should at least see your own message pop into the chat so you can work on getting "copy to clipboard" working for that one.

**Comment by Kaleshe** [comment]
No worries at all @krschacht setting up is always the most tedious part!

So now, when I get to the `bin/rails db:setup` part I receive the following error after running
```
connection to server at "127.0.0.1", port 5432 failed: fe_sendauth: no password supplied
Couldn't create 'hostedgpt_development' database. Please check your configuration.
```

Am I missing a step?
