### ISSUE TITLE
Update the app's color scheme (light & dark mode) to match the latest ChatGPT styling

### ISSUE THREAD

**Issue by krschacht** [the-dot-bot/hostedgpt#138]
Previously, the app perfectly matched the colors of ChatGPT in light and dark, but the app recently updated so we should update HostedGPT to match.

**Comment by florianfelsing** [comment]
Hi @krschacht - I'd like to take this one as my first issue.

**Comment by krschacht** [comment]
@florianfelsing That's great! Tag me in here if you have any questions. Be sure to toggle light & dark mode both within HostedGPT and within ChatGPT.

For example, I noticed that the right side background color changed in dark mode so we should match that, in addition to the left column light mode. I didn't study the other differences too closely.

**Comment by florianfelsing** [comment]
FYI, I'll be working on this one and submit my PR before the week ends. Had a bit of a stressful week.

**Comment by krschacht** [comment]
Sounds great, thanks for the heads up.
