### ISSUE TITLE
bug: when saving the user settings fails, the backend 500s

### ISSUE THREAD

**Issue by robacarp** [the-dot-bot/hostedgpt#97]
I don't really know what to do here. The turbo docs say that a failed form submission should return Unprocessable Entity, but we don't have a way to re-render the page with the modal popped up.

The correct solution may be easier when we move the modal out of the conversation view and into the layout, but I don't know if it's smart to start showing a modal from a controller flag.

**Comment by olimart** [comment]
I think this is resolved.
At least it seems to be working in 60e6d67698ca82dd8f37a8b94812c3915b3237a8
